/* Paleta, tipografia, ícones e a folha de estilos inteira.

   Fica num módulo só porque é a única coisa que absolutamente todo componente
   importa: telas, gráficos e primitivos de interface. Separar por tela criaria
   dependência cruzada entre arquivos que não deveriam se conhecer. */

const C = {
  bg: "#F2F2F7",
  card: "#FFFFFF",
  sep: "rgba(60,60,67,0.13)",
  label: "#000000",
  /* 0.725 é a menor opacidade que passa 4.5:1 (AA, texto normal) sobre os dois
     fundos usados: o card branco e o cinza da página. Em 0.6 dava 3.44:1. */
  sec: "rgba(60,60,67,0.725)",
  /* rótulo de eixo e marcador de dia vazio: 0.565 leva a 3:1, o limiar de
     elemento gráfico. Em 0.28 dava 1.67:1, quase invisível. */
  ter: "rgba(60,60,67,0.565)",
  fill: "rgba(120,120,128,0.11)",
  blue: "#007AFF",
  red: "#FF375F",
  green: "#30D158",
  orange: "#FF9F0A",
  purple: "#BF5AF2",
  indigo: "#5E5CE6",
};

/* faixa plausível de frequência cardíaca; fora disso é engano de digitação */

const font = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, sans-serif';

/* Duração e curva da abertura das folhas modais, num lugar só para não voltarem
   a divergir. A curva desacelera no fim, sem o arranque quase instantâneo da
   anterior. */
const DUR_FOLHA = ".34s";
const CURVA_FOLHA = "cubic-bezier(.32,.72,0,1)";

const s = {
  page: {
    background: "#DEDEE4",
    minHeight: "100dvh",
    display: "flex",
    justifyContent: "center",
    fontFamily: font,
    color: C.label,
  },
  phone: {
    width: "100%",
    maxWidth: 402,
    height: "100dvh",
    background: C.bg,
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 0 80px rgba(0,0,0,0.13)",
  },
  scroll: {
    height: "100%",
    overflowY: "auto",
    padding: "0 16px",
  },
  compactBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 46,
    zIndex: 15,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(242,242,247,0.82)",
    backdropFilter: "saturate(180%) blur(20px)",
    WebkitBackdropFilter: "saturate(180%) blur(20px)",
    borderBottom: `0.5px solid ${C.sep}`,
    transition: "opacity .25s ease",
  },
  largeTitle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    padding: "22px 0 10px",
  },
  h1: { fontSize: 34, fontWeight: 700, letterSpacing: "-1.1px", margin: 0 },
  link: { color: C.blue, fontSize: 17, padding: "4px 0", letterSpacing: "-0.2px" },
  linkSm: { color: C.blue, fontSize: 15, fontWeight: 500 },
  section: {
    fontSize: 12.5,
    fontWeight: 600,
    color: C.sec,
    textTransform: "uppercase",
    letterSpacing: "0.3px",
    padding: "22px 4px 8px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 10,
  },
  sectionRight: {
    fontWeight: 500,
    textTransform: "none",
    fontSize: 12.5,
    letterSpacing: 0,
    flexShrink: 0,
  },
  card: {
    background: C.card,
    borderRadius: 18,
    marginBottom: 10,
    overflow: "hidden",
    boxShadow: "0 1px 2px rgba(0,0,0,0.045), 0 8px 20px -8px rgba(0,0,0,0.06)",
  },
  eyebrow: { fontSize: 12.5, fontWeight: 600, color: C.sec, letterSpacing: "0.1px" },
  big: {
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: "-1.3px",
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1,
  },
  unit: { fontSize: 14, color: C.sec, fontWeight: 500 },
  sub: { fontSize: 13, color: C.sec, marginTop: 5, lineHeight: 1.4 },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  tile: {
    background: C.card,
    borderRadius: 18,
    padding: 15,
    boxShadow: "0 1px 2px rgba(0,0,0,0.045), 0 8px 20px -8px rgba(0,0,0,0.06)",
  },
  tileLabel: { fontSize: 12.5, fontWeight: 600, color: C.sec },
  row: { display: "flex", alignItems: "center", gap: 11, padding: "10px 0" },
  rowLabel: { fontSize: 15.5, letterSpacing: "-0.25px" },
  rowSub: { fontSize: 12.5, color: C.sec, marginTop: 2, lineHeight: 1.3 },
  rowValue: {
    fontSize: 16,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.3px",
  },

  /* faixa de dias */
  diaCol: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "6px 0 5px",
    borderRadius: 11,
    minWidth: 0,
    transition: "background .2s",
  },
  diaLetra: { fontSize: 11, letterSpacing: "0.2px" },
  diaNum: {
    fontSize: 13,
    fontWeight: 600,
    marginTop: 2,
    fontVariantNumeric: "tabular-nums",
    color: C.label,
  },
  diaNumHoje: {
    background: C.red,
    color: "#fff",
    borderRadius: 999,
    width: 21,
    height: 21,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11.5,
  },
  diaBarra: {
    width: 15,
    borderRadius: 5,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: 5,
    boxShadow: "0 1px 3px rgba(0,0,0,0.12)",
  },
  diaVazio: { width: 5, height: 5, borderRadius: 999, background: C.ter },
  diaMin: { fontSize: 11, fontWeight: 600, marginTop: 6, fontVariantNumeric: "tabular-nums" },
  diaDetalhe: {
    marginTop: 14,
    paddingTop: 12,
    borderTop: `0.5px solid ${C.sep}`,
    animation: "fade .2s ease",
  },
  metaBarOuter: { height: 7, borderRadius: 4, background: C.fill, overflow: "hidden" },
  chipHoje: {
    fontSize: 12.5,
    fontWeight: 600,
    color: C.blue,
    background: "rgba(0,122,255,0.1)",
    padding: "6px 12px",
    borderRadius: 9,
    flexShrink: 0,
  },
  setaSemana: {
    width: 32,
    height: 32,
    borderRadius: 999,
    background: C.fill,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  metaBarInner: {
    height: "100%",
    borderRadius: 4,
    background: "linear-gradient(90deg,#17B84A,#5DE86F)",
    transition: "width .7s cubic-bezier(.16,.84,.28,1)",
  },

  zoneBadge: {
    width: 22,
    height: 22,
    borderRadius: 7,
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  dot: { width: 11, height: 11, borderRadius: 3, flexShrink: 0 },
  dotSm: { width: 8, height: 8, borderRadius: 2.5, display: "inline-block", marginRight: 5 },
  legend: { fontSize: 11.5, color: C.sec, display: "flex", alignItems: "center", fontWeight: 500 },
  columnWrap: {
    width: 12,
    borderRadius: 6,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    background: C.fill,
    alignSelf: "stretch",
  },
  iconBadge: {
    width: 30,
    height: 30,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  insightHead: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 3,
  },
  insightTitle: { fontSize: 15.5, fontWeight: 600, letterSpacing: "-0.3px" },
  insightTag: {
    fontSize: 14,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.3px",
    flexShrink: 0,
  },
  insightBody: { fontSize: 13.5, color: C.sec, lineHeight: 1.47 },
  foot: { fontSize: 12.5, color: C.sec, lineHeight: 1.5, marginTop: 12, marginBottom: 0 },
  field: {
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "13px 16px",
    background: C.card,
  },
  fieldLabel: { fontSize: 15.5, flex: 1, letterSpacing: "-0.25px" },
  inputRight: { border: "none", fontSize: 15.5, textAlign: "right", color: C.sec },
  inputNum: {
    border: "none",
    fontSize: 17,
    textAlign: "right",
    width: 100,
    fontVariantNumeric: "tabular-nums",
    fontWeight: 500,
  },
  metricRow: { display: "flex", alignItems: "center", gap: 9, padding: "13px 16px", width: "100%" },
  metricValue: {
    fontSize: 16,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.3px",
    flexShrink: 0,
  },
  faixaTag: { fontSize: 11, fontWeight: 600, padding: "3px 7px", borderRadius: 6, flexShrink: 0 },
  metricNota: {
    fontSize: 12.5,
    color: C.sec,
    lineHeight: 1.5,
    margin: 0,
    padding: "0 16px 14px",
    animation: "fade .2s ease",
  },
  zoneRow: { display: "flex", alignItems: "center", gap: 11, padding: "11px 0" },
  trackOuter: { height: 3, borderRadius: 2, background: C.fill, marginTop: 7, overflow: "hidden" },
  trackInner: {
    height: "100%",
    borderRadius: 2,
    transition: "width .35s cubic-bezier(.16,.84,.28,1)",
  },
  /* gap maior que o outline-offset do foco (2px + 2.5px de traço), senão o
     anel de foco de um campo cobre o rótulo do campo vizinho */
  tempoCampo: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 },
  tempoInput: {
    /* cabe "123:45"; era 46 quando eram dois campos de dois algarismos */
    width: 74,
    background: C.fill,
    border: "none",
    borderRadius: 9,
    padding: "10px 4px",
    fontSize: 17,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 600,
  },
  tempoSep: { fontSize: 11.5, color: C.sec, fontWeight: 500 },
  totalBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    paddingTop: 14,
    borderTop: `0.5px solid ${C.sep}`,
  },
  textarea: { width: "100%", border: "none", fontSize: 15.5, resize: "vertical", lineHeight: 1.45 },
  primary: {
    width: "100%",
    background: C.red,
    color: "#fff",
    borderRadius: 15,
    padding: 15,
    fontSize: 17,
    fontWeight: 600,
    marginTop: 14,
    letterSpacing: "-0.3px",
    boxShadow: "0 6px 18px -6px rgba(255,55,95,0.6)",
  },
  secondary: {
    width: "100%",
    background: C.fill,
    color: C.blue,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    fontWeight: 500,
    marginTop: 10,
  },
  destructive: {
    width: "100%",
    background: "rgba(255,55,95,0.1)",
    color: C.red,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    fontWeight: 500,
    marginTop: 12,
  },
  error: {
    background: "rgba(255,55,95,0.1)",
    color: C.red,
    borderRadius: 12,
    padding: "13px 15px",
    fontSize: 14,
    marginTop: 12,
  },
  sesRow: { display: "flex", alignItems: "center", gap: 8, padding: "13px 16px", width: "100%" },
  miniBar: {
    display: "flex",
    height: 5,
    borderRadius: 3,
    overflow: "hidden",
    background: C.fill,
    marginTop: 8,
    width: "100%",
  },
  chev: {
    color: C.ter,
    fontSize: 22,
    transition: "transform .25s cubic-bezier(.16,.84,.28,1)",
    lineHeight: 1,
    flexShrink: 0,
  },
  detail: {
    padding: "4px 16px 16px",
    background: "rgba(120,120,128,0.045)",
    animation: "fade .2s ease",
  },
  detailRow: { display: "flex", alignItems: "center", fontSize: 14, padding: "6px 0" },
  mono: { fontVariantNumeric: "tabular-nums", fontSize: 15.5, color: C.sec, fontWeight: 500 },
  segmented: {
    display: "flex",
    background: "rgba(120,120,128,0.12)",
    borderRadius: 10,
    padding: 2,
    marginBottom: 12,
    position: "relative",
  },
  segPill: {
    position: "absolute",
    top: 2,
    bottom: 2,
    left: 2,
    background: "#fff",
    borderRadius: 8,
    boxShadow: "0 3px 8px rgba(0,0,0,0.12)",
    transition: "transform .3s cubic-bezier(.16,.84,.28,1)",
  },
  seg: {
    flex: 1,
    borderRadius: 8,
    padding: "7px 0",
    fontSize: 13,
    position: "relative",
    zIndex: 1,
    letterSpacing: "-0.1px",
  },
  tabbar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    alignItems: "flex-start",
    background: "rgba(249,249,251,0.88)",
    backdropFilter: "saturate(180%) blur(22px)",
    WebkitBackdropFilter: "saturate(180%) blur(22px)",
    borderTop: `0.5px solid ${C.sep}`,
    padding: "8px 0 24px",
    zIndex: 20,
  },
  tabBtn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    padding: 0,
  },
  fab: {
    width: 46,
    height: 46,
    borderRadius: 999,
    background: C.red,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -8,
    boxShadow: "0 6px 16px -4px rgba(255,55,95,0.65)",
  },
  toast: {
    position: "absolute",
    bottom: 100,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 45,
    background: "rgba(28,28,30,0.95)",
    color: "#fff",
    padding: "12px 20px",
    borderRadius: 24,
    fontSize: 14,
    maxWidth: 330,
    textAlign: "center",
    animation: "rise .25s ease",
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    /* posicionado absoluto encolhe até a menor largura possível e quebra a frase
       sem precisar; max-content faz caber numa linha até o limite acima */
    width: "max-content",
  },
  toastAcao: {
    color: "#4DA3FF",
    fontSize: 14,
    fontWeight: 600,
    flexShrink: 0,
    padding: "2px 2px",
    marginLeft: 2,
  },
  /* O escurecimento saiu daqui para uma camada própria. Estava neste contêiner,
     com `fade` aplicado ao conjunto — e como a folha é filha dele, ela subia
     translúcida: dava para ler a tela de trás através do formulário durante toda
     a animação. A folha agora é opaca desde o primeiro quadro, e só o escuro
     aparece aos poucos. */
  sheetWrap: {
    position: "absolute",
    inset: 0,
    zIndex: 40,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    /* o gesto que sobra na folha não pode virar rolagem da tela de trás */
    overscrollBehavior: "contain",
  },
  /* Mesma duração e mesma curva da folha, de propósito. Antes eram .34s numa
     curva muito adiantada e .25s noutra: a folha chegava ao lugar por volta dos
     90 ms com o fundo ainda a 44% do escuro, que continuava escurecendo sozinho
     por mais 160 ms. Eram dois movimentos onde devia haver um. */
  /* `touchAction: none` declarado no estilo, e não aplicado ao abrir: no iOS o
     alvo do gesto é escolhido quando o dedo encosta, então quem chega depois
     chega tarde. Vale para toda superfície da folha que não rola — o fundo
     escurecido, a alça e o cabeçalho. Nunca para o conteúdo, que precisa rolar. */
  sheetFundo: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.34)",
    animation: `fade ${DUR_FOLHA} ${CURVA_FOLHA}`,
    touchAction: "none",
  },
  sheet: {
    width: "100%",
    maxHeight: "94%",
    background: C.bg,
    borderRadius: "14px 14px 0 0",
    animation: `sheetIn ${DUR_FOLHA} ${CURVA_FOLHA}`,
    display: "flex",
    flexDirection: "column",
    /* sem isto os cantos arredondados não recortam o conteúdo que rola por baixo */
    overflow: "hidden",
    /* posicionada para ficar acima da camada escura, que é irmã e vem antes */
    position: "relative",
  },
  sheetConteudo: {
    /* instalado na tela de início a folha encosta no indicador de home; 34 px
       continuam valendo onde não há área segura a respeitar */
    padding: "0 16px max(34px, env(safe-area-inset-bottom))",
    overflowY: "auto",
    /* Ao chegar ao topo do formulário, o resto do gesto ia rolar a tela de trás:
       a folha parecia travada e o fundo é que se mexia. */
    overscrollBehavior: "contain",
  },
  grabber: {
    width: 36,
    height: 5,
    borderRadius: 3,
    background: "rgba(60,60,67,0.28)",
    margin: "8px auto 0",
    touchAction: "none",
  },
  navMes: {
    display: "flex", alignItems: "center", gap: 10, padding: "6px 4px 10px",
  },
  navMesCentro: { flex: 1, minWidth: 0, textAlign: "center" },
  navMesTitulo: { fontSize: 15.5, fontWeight: 600, letterSpacing: "-0.2px" },
  confirmWrap: {
    position: "absolute", inset: 0, zIndex: 50, background: "rgba(0,0,0,0.4)", touchAction: "none",
    display: "flex", alignItems: "center", justifyContent: "center", padding: 24,
    animation: "fade .18s ease",
  },
  confirmCaixa: {
    background: C.card, borderRadius: 18, padding: "22px 20px 18px", width: "100%", maxWidth: 320,
    boxShadow: "0 12px 40px rgba(0,0,0,0.28)", textAlign: "center",
  },
  confirmTitulo: { fontSize: 17, fontWeight: 600, letterSpacing: "-0.3px", display: "block" },
  confirmTexto: { fontSize: 14, color: C.sec, lineHeight: 1.45, margin: "8px 0 4px" },
  sheetHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px 8px",
    touchAction: "none",
  },
  done: { color: C.blue, fontSize: 17, fontWeight: 600 },

  recWrap: {
    minHeight: "100dvh",
    background: C.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    /* renderiza fora do Shell, então precisa declarar a fonte por conta própria */
    fontFamily: font,
    color: C.label,
  },
  recCard: {
    background: C.card,
    borderRadius: 22,
    padding: "26px 22px 22px",
    maxWidth: 380,
    width: "100%",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  recTitulo: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.5px", margin: "0 0 8px" },
  recTexto: { fontSize: 14.5, color: C.sec, lineHeight: 1.5, margin: "0 0 18px" },
  recDetalhe: {
    fontSize: 11.5,
    color: C.sec,
    lineHeight: 1.45,
    marginTop: 18,
    marginBottom: 0,
    wordBreak: "break-word",
  },
};

const FAIXA_COR = { baixo: C.blue, bom: C.green, ok: C.green, atencao: C.orange, alto: C.red };
const FAIXA_TXT = {
  baixo: "baixo",
  bom: "na faixa",
  ok: "aceitável",
  atencao: "atenção",
  alto: "alto",
};

const ICONS = {
  carga: "M3 17l5-6 4 4 6-8",
  zonas: "M4 19V9M9.5 19V5M15 19v-7M20.5 19v-4",
  coracao: "M12 20s-7-4.5-7-9.5A3.9 3.9 0 0112 8a3.9 3.9 0 017 2.5C19 15.5 12 20 12 20z",
  raio: "M13 3L5 14h6l-1 7 8-11h-6l1-7z",
  meta: "M5 12l4.5 4.5L19 7",
  relogio: "M12 7v5l3 2M12 21a9 9 0 100-18 9 9 0 000 18z",
  balanca: "M12 4v16M5 8h14M7 8l-3 6h6zM17 8l-3 6h6z",
  calendario:
    "M4 8h16M8 3v3M16 3v3M5 21h14a1 1 0 001-1V7a1 1 0 00-1-1H5a1 1 0 00-1 1v13a1 1 0 001 1z",
};

export { C, font, s, FAIXA_COR, FAIXA_TXT, ICONS };
